#
# Don't edit this file
#
[mv]
method = "move_all_angles_sync"
paramtype = "angles"
info = "move all servos (e.g. mv:30,-20  mv:c,n,x  mv:.,=,c,30)"
[mr]
method = "move_all_angles_sync_relative"
paramtype = "angle_diffs"
info = "move all servos relative (e.g. mr:10,-20)"
[sl]
method = "sleep"
paramtype = "sec"
info = "sleep (e.g. sl:1  sl:.5)"
[ms]
method = "move_sec"
paramtype = "sec"
info = "set move second (e.g. ms:1  ms:.5)"
[st]
method = "step_n"
paramtype = "step_n"
info = "set number of steps (e.g. st:50  st:2)"
[is]
method = "interval"
paramtype = "sec"
info = "set interval (e.g. is:1  is:.5)"
[mp]
method = "move_pulse_relative"
paramtype = "move_pulse"
info = "move single servo by pulse (e.g. mp:0,100  mp:1,-200)"
[cb]
method = "set"
paramtype = "calib"
info = "calibrate single servo (e.g. cb:0,c  cb:1,n,500  cb:2,x,2500)"
[qq]
method = "qsize"
paramtype = ""
info = "get queue size"
[ww]
method = "wait"
paramtype = ""
info = "wait for competion"
[zz]
method = "cancel"
paramtype = ""
info = "cancel all queued commands"
